### ISSUE TITLE
Failed to run upgrade safety validation

### ISSUE THREAD

**Issue by therealharpaljadeja** [OpenZeppelin/openzeppelin-foundry-upgrades#59]
I am using `openzeppelin-foundry-upgrades`, openzeppelin contracts v5 and using the following code snippet in my `setUp()` function in foundry test.

```solidity
 proxy = Upgrades.deployTransparentProxy(
      'Token.sol',
      tokenOwner,
      abi.encodeCall(Token.initialize, tokenOwner)
 );
```

`foundry.toml`
```toml
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
```

OS: macOS Sonoma

I get the following error when running `forge test`. Compilation works, tests fail.

<img width="1426" alt="image" src="https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/assets/38040789/474678f1-4045-4858-8ec6-c3e064adc206">
